### required libraries


In [95]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import pylab as pl
from sklearn import preprocessing

### open file

In [96]:
Iris_df = pd.read_csv("Iris.csv")
print(Iris_df.dtypes)
Iris_df.head()


Sepal_Length    float64
Sepal_Width     float64
Petal_Length    float64
Petal_Width     float64
Class            object
dtype: object


Sepal_Length  Sepal_Width  Petal_Length  Petal_Width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

### clear data

In [97]:
print (Iris_df.info())
Iris_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Sepal_Length  150 non-null    float64
 1   Sepal_Width   150 non-null    float64
 2   Petal_Length  150 non-null    float64
 3   Petal_Width   150 non-null    float64
 4   Class         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

### defin x &  y 

In [98]:
feature_df = Iris_df[['Sepal_Length', 'Sepal_Width','Petal_Length','Petal_Width']]
X = np.asarray(feature_df)
X[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [99]:
Iris_df['Class'] = Iris_df['Class'].astype('object')
y = np.asarray(Iris_df['Class'])
y [0:20]

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
      dtype=object)

### Data separation

In [100]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split( X, y, test_size=0.2 ,random_state=50)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (120, 4) (120,)
Test set: (30, 4) (30,)


### Training of the KNN algorithm for the model

In [101]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
y_true = y
y_pred

array(['Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica'],
      dtype=object)

### calculating the confusion matrix

In [102]:
from sklearn.metrics import confusion_matrix

labels = np.unique(y_train)
y_test_numeric = np.array([np.where(labels == label)[0][0] for label in y_test])
y_pred_numeric = np.array([np.where(labels == label)[0][0] for label in y_pred])

cm = confusion_matrix(y_test_numeric, y_pred_numeric)
print(cm)

[[ 9  0  0]
 [ 0 11  1]
 [ 0  0  9]]


### calculating the precision,recall,jaccard,accuracy

In [103]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import jaccard_score
from sklearn.metrics import accuracy_score
precision_macro = precision_score(y_test_numeric, y_pred_numeric, average='macro')
recall_macro = recall_score(y_test_numeric, y_pred_numeric, average='macro')
jaccard_macro = jaccard_score(y_test_numeric, y_pred_numeric, average='macro')
accuracy = accuracy_score(y_test, y_pred)
print("Precision with macro-averaging:         ", precision_macro)
print("Recall with macro-averaging:            ", recall_macro)
print("Jaccard similarity with macro-averaging:", jaccard_macro)
print('Accuracy:                               ', accuracy)

Precision with macro-averaging:          0.9666666666666667
Recall with macro-averaging:             0.9722222222222222
Jaccard similarity with macro-averaging: 0.9388888888888888
Accuracy:                                0.9666666666666667


### normalizing

In [104]:
feature_df = Iris_df[['Sepal_Length','Sepal_Width','Petal_Length','Petal_Width']]
X = np.asarray(feature_df)
Scaler= preprocessing.StandardScaler().fit(X)
X =Scaler.transform(X.astype(float))
print(X[0:10])

[[-0.90068117  1.03205722 -1.3412724  -1.31297673]
 [-1.14301691 -0.1249576  -1.3412724  -1.31297673]
 [-1.38535265  0.33784833 -1.39813811 -1.31297673]
 [-1.50652052  0.10644536 -1.2844067  -1.31297673]
 [-1.02184904  1.26346019 -1.3412724  -1.31297673]
 [-0.53717756  1.95766909 -1.17067529 -1.05003079]
 [-1.50652052  0.80065426 -1.3412724  -1.18150376]
 [-1.02184904  0.80065426 -1.2844067  -1.31297673]
 [-1.74885626 -0.35636057 -1.3412724  -1.31297673]
 [-1.14301691  0.10644536 -1.2844067  -1.4444497 ]]


### Data separation

In [105]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split( X, y, test_size=0.2 ,random_state=50)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (120, 4) (120,)
Test set: (30, 4) (30,)


### Training of the KNN algorithm for the model

In [106]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
y_true = y
y_pred

array(['Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica'],
      dtype=object)

### calculating the confusion matrix

In [107]:
from sklearn.metrics import confusion_matrix
y_pred = knn.predict(X_test)

labels = np.unique(y_train)
y_test_numeric = np.array([np.where(labels == label)[0][0] for label in y_test])
y_pred_numeric = np.array([np.where(labels == label)[0][0] for label in y_pred])

cm = confusion_matrix(y_test_numeric, y_pred_numeric)
print(cm)

[[ 9  0  0]
 [ 0 10  2]
 [ 0  0  9]]


### calculating the precision,recall,jaccard,accuracy

In [108]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import jaccard_score
from sklearn.metrics import accuracy_score
precision_macro = precision_score(y_test_numeric, y_pred_numeric, average='macro')
recall_macro = recall_score(y_test_numeric, y_pred_numeric, average='macro')
jaccard_macro = jaccard_score(y_test_numeric, y_pred_numeric, average='macro')
print("Precision with macro-averaging:         ", precision_macro)
print("Recall with macro-averaging:            ", recall_macro)
print("Jaccard similarity with macro-averaging:", jaccard_macro)
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:                               ', accuracy)

Precision with macro-averaging:          0.9393939393939394
Recall with macro-averaging:             0.9444444444444445
Jaccard similarity with macro-averaging: 0.883838383838384
Accuracy:                                0.9333333333333333
